<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class School_year extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('School_year_model');
    } 

    /*
     * Listing of school_year
     */
    function index()
    {
        $data['school_year'] = $this->School_year_model->get_all_school_year();
        
        $data['_view'] = 'school_year/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new school_year
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('schoolyear_status','Schoolyear Status','required|integer');
		$this->form_validation->set_rules('schoolyear_value','Schoolyear Value','required|max_length[20]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'schoolyear_status' => $this->input->post('schoolyear_status'),
				'schoolyear_value' => $this->input->post('schoolyear_value'),
            );
            
            $school_year_id = $this->School_year_model->add_school_year($params);
            redirect('school_year/index');
        }
        else
        {            
            $data['_view'] = 'school_year/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a school_year
     */
    function edit($schoolyear_id)
    {   
        // check if the school_year exists before trying to edit it
        $data['school_year'] = $this->School_year_model->get_school_year($schoolyear_id);
        
        if(isset($data['school_year']['schoolyear_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('schoolyear_status','Schoolyear Status','required|integer');
			$this->form_validation->set_rules('schoolyear_value','Schoolyear Value','required|max_length[20]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'schoolyear_status' => $this->input->post('schoolyear_status'),
					'schoolyear_value' => $this->input->post('schoolyear_value'),
                );

                $this->School_year_model->update_school_year($schoolyear_id,$params);            
                redirect('school_year/index');
            }
            else
            {
                $data['_view'] = 'school_year/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The school_year you are trying to edit does not exist.');
    }
}
 