<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Subject extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Subject_model');
    } 

    /*
     * Listing of subjects
     */
    function index()
    {
        $data['subjects'] = $this->Subject_model->get_all_subjects();
        $data['page_title'] = 'Subjects';
        $data['_view'] = 'subject/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new subject
     */
    function add()
    {   
        $this->load->library('form_validation');
        $data['page_title'] = 'Add New Subject';
		$this->form_validation->set_rules('code','Code','required|max_length[100]');
		$this->form_validation->set_rules('name','Name','required|max_length[100]');
		$this->form_validation->set_rules('description','Description','required|max_length[100]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'code' => $this->input->post('code'),
				'name' => $this->input->post('name'),
				'description' => $this->input->post('description'),
            );
            
            $subject_id = $this->Subject_model->add_subject($params);
            redirect('subject/index');
        }
        else
        {            
            $data['_view'] = 'subject/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a subject
     */
    function edit($id)
    {   
        // check if the subject exists before trying to edit it
        $data['subject'] = $this->Subject_model->get_subject($id);
        
        if(isset($data['subject']['id']))
        {
            $this->load->library('form_validation');
            $data['page_title'] = 'Edit Existing Subject';
			$this->form_validation->set_rules('code','Code','required|max_length[100]');
			$this->form_validation->set_rules('name','Name','required|max_length[100]');
			$this->form_validation->set_rules('description','Description','required|max_length[100]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'code' => $this->input->post('code'),
					'name' => $this->input->post('name'),
					'description' => $this->input->post('description'),
                );

                $this->Subject_model->update_subject($id,$params);            
                redirect('subject/index');
            }
            else
            {
                $data['_view'] = 'subject/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The subject you are trying to edit does not exist.');
    }
}