<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Charge_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get charge by charge_id
     */
    function get_charge($charge_id)
    {
        return $this->db->get_where('charges',array('charge_id'=>$charge_id))->row_array();
    }
        
    function get_all_charges_by_id($level){
        return $this->db->where('charge_level',$level)->get('charges')->result();
    }

    /*
     * Get all charges
     */
    function get_all_charges()
    {
        $this->db->order_by('charge_id', 'Asc');
        return $this->db->get('charges')->result_array();
    }
        
    /*
     * function to add new charge
     */
    function add_charge($params)
    {
        $this->db->insert('charges',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update charge
     */
    function update_charge($charge_id,$params)
    {
        $this->db->where('charge_id',$charge_id);
        return $this->db->update('charges',$params);
    }
    
    /*
     * function to delete charge
     */
    function delete_charge($charge_id)
    {
        return $this->db->delete('charges',array('charge_id'=>$charge_id));
    }
}