<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Faculty_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get faculty by id
     */
    function get_faculty($id)
    {
        return $this->db->get_where('faculty',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all faculty
     */
    function get_all_faculty()
    {
        $this->db->order_by('id', 'ASC');
        return $this->db->get('faculty')->result_array();
    }
        
    /*
     * function to add new faculty
     */
    function add_faculty($params)
    {
        $this->db->insert('faculty',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update faculty
     */
    function update_faculty($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('faculty',$params);
    }
    
    /*
     * function to delete faculty
     */
    function delete_faculty($id)
    {
        return $this->db->delete('faculty',array('id'=>$id));
    }

    function get_faculty_subjects($id){
        return $this->db->where('teacher',$id)->get('schedules')->result_array();
    }

    function get_subject_detail_by_id($subject_id,$detail){

        return $this->db->where('id',$subject_id)->get('subjects')->row()->$detail;
    }

    function get_room_detail_by_id($room_id,$detail){

        return $this->db->where('id',$room_id)->get('rooms')->row()->$detail;
    }

    function get_level_detail_by_id($level_id,$detail){

        return $this->db->where('levels_id',$level_id)->get('levels')->row()->$detail;
    }

    function get_section_detail_by_id($section_id,$detail){

        return $this->db->where('id',$section_id)->get('sections')->row()->$detail;   
    }

    function add_faculty_subject($data){
        return $this->db->insert('schedules',$data);
    }


}