<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class School_year_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get school_year by schoolyear_id
     */
    function get_school_year($schoolyear_id)
    {
        return $this->db->get_where('school_year',array('schoolyear_id'=>$schoolyear_id))->row_array();
    }
        
    /*
     * Get all school_year
     */
    function get_all_school_year()
    {
        $this->db->order_by('schoolyear_id', 'desc');
        return $this->db->get('school_year')->result_array();
    }
        
    /*
     * function to add new school_year
     */
    function add_school_year($params)
    {
        $this->db->insert('school_year',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update school_year
     */
    function update_school_year($schoolyear_id,$params)
    {
        $this->db->where('schoolyear_id',$schoolyear_id);
        return $this->db->update('school_year',$params);
    }
    
    /*
     * function to delete school_year
     */
    function delete_school_year($schoolyear_id)
    {
        return $this->db->delete('school_year',array('schoolyear_id'=>$schoolyear_id));
    }

    function deactivate_previous_schoolyear(){
        $data =['schoolyear_status'=>0];

        $prev =  $this->db->where('schoolyear_status',1)->get('school_year')->row()->schoolyear_id;

        return $this->db->where('schoolyear_id',$prev)->update('school_year',$data);
    }
}