<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Section_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get section by id
     */
    function get_section($id)
    {
        return $this->db->get_where('sections',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all sections
     */
    function get_all_sections()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('sections')->result_array();
    }
        
    /*
     * function to add new section
     */
    function add_section($params)
    {
        $this->db->insert('sections',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update section
     */
    function update_section($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('sections',$params);
    }
    
    /*
     * function to delete section
     */
    function delete_section($id)
    {
        return $this->db->delete('sections',array('id'=>$id));
    }

    function get_vacant_teachers(){

        return $this->db->query('SELECT * FROM faculty fc WHERE NOT EXISTS ( SELECT * FROM sections sec WHERE sec.adviser = fc.id )')
            ->result();
    }

}