<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Student_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get student by id
     */
    function get_student($id)
    {
        return $this->db->get_where('students',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all students count
     */
    function get_all_students_count()
    {
        $this->db->from('students');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all students
     */
    function get_all_students($params = array())
    {
       
        return $this->db->get('students')->result_array();
    }
        
    /*
     * function to add new student
     */
    function add_student($params)
    {
        $this->db->insert('students',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update student
     */
    function update_student($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('students',$params);
    }
    
    /*
     * function to delete student
     */
    function delete_student($id)
    {
        return $this->db->delete('students',array('id'=>$id));
    }

    function insert_additional_info($data){

         $this->db->insert('guardian',$data);
         return $this->db->insert_id();
    }

    function update_guardian_info($data,$id){

     $this->db->where('id',$id);
        return $this->db->update('guardian',$data);
    }

    function get_guardian($id){

        return $this->db->where('student_id',$id)->get('guardian')->result_array();
    }

    function get_level($level_id){
        if(!is_null($level_id)){
            return $this->db->where('levels_id',$id)->get('levels')->result_array();
        }else{
            return $this->db->get('levels');
        }
    }

    function get_section($year_level){
        if(!is_null($year_level)){
            return $this->db->where('level',$year_level)->get('sections')->result_array();
        }else{
            return $this->db->get('sections')->result_array();
        }
    }
    function get_student_fullname($student_id){
        return $this->db->where('id',$student_id)->get('students')->row();
    }

    function get_student_grade($student_id,$teacher_id,$school_year){

        return $this->db->join('grades', 'grades.subject_id = schedules.subject')
                        ->where('schedules.teacher',$teacher_id)
                        ->where('grades.schoolyear_id',$school_year)
                        ->where('grades.student_id',$student_id)
                        ->get('schedules')
                        ->result();
    }

    function get_student_id_from_table_users($email){

        return $this->db->where('email',$email)->get('users')->row()->id;
    }

    function get_student_id_from_table_students_by_email($student_email){

        return $this->db->where('email',$student_email)->get('students')->row()->id;
    }
}
